services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8081:8081"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8081/tcp,8081/udp
    volumes:
      - /home/raspberrypi/home-pi-server/qbittorrent/config:/config
      - /mnt/hdd/downloads:/downloads
      - /mnt/hdd/media:/media